\documentclass{article}
\usepackage{graphicx, hyperref}
\usepackage[margin=1in]{geometry}
\usepackage[backend=bibtex, natbib=true]{biblatex}
\newtheorem{rexample}{R Example}[section]
\addbibresource{references.bib}

\setlength{\parskip}{3ex}
\setlength{\parindent}{0pt}

\title{A Web Application for Efficient Analysis of Peptide Libraries}
\author{Eric Riemer Hare}

\begin{document}

\maketitle
\clearpage

<<libraries, echo=FALSE, cache=FALSE, message=FALSE>>=
    library(peptider)
    library(shiny)
@

\section{Introduction}

\section{Shiny}

\section{User Interface}

\section{Features}

\section{Conclusion}

\end{document}
