\documentclass{article}
\usepackage{graphicx, hyperref}
\usepackage[margin=1in]{geometry}
\usepackage[backend=bibtex, natbib=true]{biblatex}
\usepackage{float}    % for fig.pos='H'
\newtheorem{rexample}{R Example}[section]
\addbibresource{references.bib}

\setlength{\parskip}{3ex}
\setlength{\parindent}{0pt}

\title{A Web Application for Efficient Analysis of Peptide Libraries}
\author{Eric Riemer Hare}

\begin{document}

\maketitle
\clearpage

<<libraries, echo=FALSE, cache=FALSE, message=FALSE>>=
    library(peptider)
    library(shiny)
@

\section{Introduction}
With the introduction of the R package {\it peptider}, analysis of the statistical properties of various peptide libraries is now possible. However, use of this package still requires familiarity with the R language, and more general programming concepts. In this paper, I introduce a new web interface called {\it PeLiCa} (or Peptide Library Calculator) which provides a useable and flexible front-end to peptider. PeLiCa is designed for biologists and others working with peptide libraries, and does not require programming knowledge to conduct an analysis.

\section{Structure}
PeLiCa is a Shiny application[REF]

\section{User Interface}
Similar to other Shiny applications, PeLiCa consists of three primary UI components, the Configuration Panel, the Tab Panel, and the Results Panel, each illustrated in Figure \ref{fig:ui-components}. The Configuration Panel is located along the left-hand column. This panel allows for various parameters of peptide libraries to be adjusted, and some configuration options relating to PeLiCa to be changed depending on user preference. The top panel is the Tab Panel, which contains various tabs corresponding to different properties of peptide libraries that can be investigated. The bottom panel is the Results panel, which will contain the results of the analysis depending on the tab and configuration options selected.

\begin{figure}[H]
  \centering
    \includegraphics[width=\textwidth]{figure/pelica-ui.png}
  \caption{Screenshot of PeLiCa indicating the three primary UI components. (1) The Configuration Panel (2) The Tab Panel (3) The Results Panel.}
  \label{fig:ui-components}
\end{figure}

Another important component of the user interface are the help tooltips. Throughout the application, blue question marks will be available. When the user moves their mouse cursor over these icons, helpful tooltips will appear to instruct the user on how to proceed, or provide more information about the library property being investigated.

\section{Features}
The first set of features available in PeLiCa involve the specification of properties of the library of interest. These features are displayed in Figure \ref{fig:library-properties}. Users can first select a library scheme. PeLiCa provides several built-in library schemes, the first of which is the NNN scheme, in which all four bases (Adenine, Guanine, Cytosine, and Thymine) can occur at all three positions in a particular codon. The second is the NNB scheme, where the first two positions are unrestricted, but the third position can only be three bases. The third is NNK/S, which covers both NNK and NNS schemes, with the third position restricted to two bases. Both NNK and NNS have identical statistical properties in the analysis available in PeLiCa[REF]. Finally, there are trimer-based libraries in which the codons are pre-defined. PeLiCa also includes variations of these four library types in which Cysteine is treated as a non-viable amino acid.

\begin{figure}[H]
  \centering
    \includegraphics[width=0.5\textwidth]{figure/library-properties.png}
  \caption{The Library Properties section of the Configuration Panel.}
  \label{fig:library-properties}
\end{figure}

PeLiCa also has support for user-defined library schemes. If the user selects ``Custom Scheme" for the library scheme, they will be presented with an upload dialog, along with a set of instructions for uploading a custom scheme. Using a custom scheme with PeLiCa requires a minimal use of programming and may be less suitable for those unfamiliar with R.

Users can also specify the peptide length and the library size. Peptide lengths can range from six to ten amino acids, with support for larger peptides coming soon. The library size is specified in scientific notation of the form $x \times 10^y$. The user will specify values for $x$ and $y$ in this equation. $x$ can range from 1.0 to 9.9 in increments of 0.1, and $y$ can range from six to 14 in increments of one, yielding a supported range of library sizes between $1.0 \times 10^6$ and $9.9 \times 10^{14}$. Support for large library sizes is also in progress.

\begin{figure}[H]
  \centering
    \includegraphics[width=0.5\textwidth]{figure/peptide-of-interest.png}
  \caption{The Peptide of Interest section of the Configuration Panel.}
  \label{fig:peptide-of-interest}
\end{figure}

\begin{figure}[H]
  \centering
    \includegraphics[width=0.5\textwidth]{figure/configuration.png}
  \caption{The Configuration section of the Configuration Panel.}
  \label{fig:configuration}
\end{figure}

\section{Further Work}

\section{Conclusion}

\end{document}
